/*
 * SSSOM-Java - SSSOM library for Java
 * Copyright © 2024 Damien Goutte-Gattat
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the Gnu General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

package org.incenp.obofoundry.sssom;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.incenp.obofoundry.sssom.model.ExtensionDefinition;
import org.incenp.obofoundry.sssom.model.ExtensionValue;
import org.incenp.obofoundry.sssom.model.Mapping;
import org.incenp.obofoundry.sssom.model.MappingSet;
import org.incenp.obofoundry.sssom.model.ValueType;
import org.incenp.obofoundry.sssom.model.Version;
import org.incenp.obofoundry.sssom.slots.CurieMapSlot;
import org.incenp.obofoundry.sssom.slots.DateSlot;
import org.incenp.obofoundry.sssom.slots.DoubleSlot;
import org.incenp.obofoundry.sssom.slots.EntityReferenceSlot;
import org.incenp.obofoundry.sssom.slots.ExtensionDefinitionSlot;
import org.incenp.obofoundry.sssom.slots.ExtensionSlot;
import org.incenp.obofoundry.sssom.slots.Slot;
import org.incenp.obofoundry.sssom.slots.SlotHelper;
import org.incenp.obofoundry.sssom.slots.SlotPropagator;
import org.incenp.obofoundry.sssom.slots.SlotVisitorBase;
import org.incenp.obofoundry.sssom.slots.StringSlot;
import org.incenp.obofoundry.sssom.slots.VersionSlot;
import org.incenp.obofoundry.sssom.util.JSONBuilder;

/**
 * A writer to serialise a SSSOM mapping set into a JSON format.
 * <p>
 * The JSON format generated by this writer is <em>not</em> the JSON format used
 * by SSSOM-Py! SSSOM-Py uses a JSON-LD format that, for now, is completely
 * unspecified. Instead, this writer produces a “pure” JSON format that is
 * merely a direct JSON rendering of the internal SSSOM data model.
 */
public class JSONWriter extends SSSOMWriter {

    private Writer writer;
    private JSONBuilder builder = new JSONBuilder();
    private boolean shortenIRIs = false;
    private boolean curieMapInContext = false;

    /**
     * Creates a new instance that will write data to the specified file.
     * 
     * @param file The file to write the mapping set to.
     * @throws IOException If the file cannot be opened for any reason.
     */
    public JSONWriter(File file) throws IOException {
        writer = new FileWriter(file);
    }

    /**
     * Creates a new instance that will write data to the specified stream.
     * 
     * @param stream The stream to write the mapping set to.
     */
    public JSONWriter(OutputStream stream) {
        writer = new OutputStreamWriter(stream);
    }

    /**
     * Creates a new instance that will write data to a file with the specified
     * filename.
     * 
     * @param filename The name of the file to write the mapping set to.
     * @throws IOException If the file cannot be opened for any reason.
     */
    public JSONWriter(String filename) throws IOException {
        writer = new FileWriter(new File(filename));
    }

    /**
     * Enables or disables shortening of identifiers. If enabled, all identifiers
     * will be written as CURIEs and a <em>curie_map</em> will be included in the
     * output.
     * 
     * @param shorten {@code True} to enable shortening of all identifiers. It is
     *                disabled by default.
     */
    public void setShortenIRIs(boolean shorten) {
        shortenIRIs = shorten;
    }

    /**
     * Enables writing the curie map in a JSON-LD-like "@context" object.
     * <p>
     * SSSOM-Py expects the prefix names to be declared in the <em>@context</em>
     * dictionary, so this option enables that behaviour. Note that it only has
     * effect is shortening of IRIs (see {@link #setShortenIRIs(boolean)}) is also
     * enabled, because there is no curie map to write otherwise.
     * 
     * @param enabled {@code True} to write the curie map as a <em>@context</em>
     *                dictionary. The default is to write it as a normal
     *                <em>curie_map</em> slot.
     */
    public void setWriteCurieMapInContext(boolean enabled) {
        curieMapInContext = enabled;
    }

    /**
     * Serialises a mapping set into the underlying file.
     * 
     * @param mappingSet The mapping set to serialise.
     * @throws IOException If an I/O error occurs.
     */
    @Override
    protected void doWrite(MappingSet mappingSet) throws IOException {
        // Condense the set
        Set<String> condensedSlots = new SlotPropagator(condensationPolicy).condense(mappingSet, true);

        // Determine minimum compliant version
        mappingSet.setSssomVersion(Version.getCompliantVersion(mappingSet));

        if ( shortenIRIs ) {
            // Write the CURIE map
            Set<String> usedPrefixes = getUsedPrefixes(mappingSet);
            if ( !usedPrefixes.isEmpty() ) {
                builder.addKey(curieMapInContext ? "@context" : "curie_map");
                builder.startDict();
                List<String> sortedPrefixes = new ArrayList<String>(getUsedPrefixes(mappingSet));
                sortedPrefixes.sort((a, b) -> a.compareTo(b));
                for ( String prefixName : sortedPrefixes ) {
                    if ( prefixName != null ) {
                        builder.addKey(prefixName);
                        builder.addValue(prefixManager.getPrefix(prefixName));
                    }
                }
                builder.endDict();
            }
        }

        // Write the rest of the set metadata
        SlotVisitor<MappingSet> visitor = new SlotVisitor<MappingSet>();
        SlotHelper.getMappingSetHelper().visitSlots(mappingSet, visitor);

        // Write the mappings
        builder.addKey("mappings");
        builder.startList();
        SlotHelper<Mapping> helper = SlotHelper.getMappingHelper(true);
        helper.excludeSlots(condensedSlots);
        SlotVisitor<Mapping> vm = new SlotVisitor<Mapping>();
        for ( Mapping m : mappingSet.getMappings() ) {
            builder.startDict();
            helper.visitSlots(m, vm);
            builder.endDict();
        }
        builder.endList();

        writer.append(builder.close());
        writer.close();
    }

    /*
     * Visit all slots in a mapping or mapping set to render their values in JSON.
     */
    private class SlotVisitor<T> extends SlotVisitorBase<T> {

        @Override
        public void visit(Slot<T> slot, T object, Object value) {
            builder.addKey(slot.getName());
            builder.addValue(value.toString());
        }

        @Override
        public void visit(EntityReferenceSlot<T> slot, T object, String value) {
            builder.addKey(slot.getName());
            builder.addValue(shortenIRIs ? prefixManager.shortenIdentifier(value) : value);
        }

        @Override
        public void visit(StringSlot<T> slot, T object, List<String> values) {
            if ( values.size() > 0 ) {
                builder.addKey(slot.getName());
                builder.startList();
                for ( String value : values ) {
                    builder.addValue(value);
                }
                builder.endList();
            }
        }

        @Override
        public void visit(EntityReferenceSlot<T> slot, T object, List<String> values) {
            if ( values.size() > 0 ) {
                builder.addKey(slot.getName());
                builder.startList();
                for ( String value : values ) {
                    builder.addValue(shortenIRIs ? prefixManager.shortenIdentifier(value) : value);
                }
                builder.endList();
            }
        }

        @Override
        public void visit(DoubleSlot<T> slot, T object, Double value) {
            builder.addKey(slot.getName());
            builder.addValue(value);
        }

        @Override
        public void visit(DateSlot<T> slot, T object, LocalDate value) {
            builder.addKey(slot.getName());
            builder.addValue(SSSOMUtils.format(value));
        }

        @Override
        public void visit(CurieMapSlot<T> slot, T object, Map<String, String> curieMap) {
            // Nothing to do, we wrote the Curie map (if needed) already
        }

        @Override
        public void visit(VersionSlot<T> slot, T object, Version value) {
            if ( value != Version.SSSOM_1_0 && value != Version.UNKNOWN ) {
                builder.addKey(slot.getName());
                builder.addValue(value.toString());
            }
        }

        @Override
        public void visit(ExtensionDefinitionSlot<T> slot, T object, List<ExtensionDefinition> definitions) {
            if ( extraPolicy == ExtraMetadataPolicy.DEFINED && !definitions.isEmpty() ) {
                builder.addKey("extension_definitions");
                builder.startList();
                for ( ExtensionDefinition definition : definitions ) {
                    builder.startDict();
                    builder.addKey("slot_name");
                    builder.addValue(definition.getSlotName());
                    builder.addKey("property");
                    builder.addValue(shortenIRIs ? prefixManager.shortenIdentifier(definition.getProperty())
                            : definition.getProperty());
                    if ( definition.getEffectiveType() != ValueType.STRING ) {
                        builder.addKey("type_hint");
                        builder.addValue(shortenIRIs ? prefixManager.shortenIdentifier(definition.getTypeHint())
                                : definition.getTypeHint());
                    }
                    builder.endDict();
                }
                builder.endList();
            }
        }

        @Override
        public void visit(ExtensionSlot<T> slot, T object, Map<String, ExtensionValue> extensions) {
            if ( extraPolicy != ExtraMetadataPolicy.NONE ) {
                for ( ExtensionDefinition definition : extensionManager.getDefinitions(true, false) ) {
                    ExtensionValue value = extensions.get(definition.getProperty());
                    if ( value != null ) {
                        builder.addKey(definition.getSlotName());
                        switch ( value.getType() ) {
                        case BOOLEAN:
                            builder.addValue(value.asBoolean());
                            break;
                        case DOUBLE:
                            builder.addValue(value.asDouble());
                            break;
                        case INTEGER:
                            builder.addValue(value.asInteger());
                            break;
                        case IDENTIFIER:
                            builder.addValue(
                                    shortenIRIs ? prefixManager.shortenIdentifier(value.asString()) : value.asString());
                            break;
                        default:
                            builder.addValue(value.toString());
                            break;
                        }
                    }
                }
            }
        }
    }
}
